name: mne_new
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.12.14=hbcca054_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgomp=14.2.0=h77fa898_1
  - liblzma=5.6.3=hb9d3cd8_1
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.47.2=hee588c1_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=he02047a_1
  - openssl=3.4.0=h7b32b05_1
  - pip=24.3.1=pyh8b19718_2
  - python=3.10.16=he725a3c_1_cpython
  - readline=8.2=h8228510_1
  - setuptools=75.6.0=pyhff2d567_1
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - absl-py==2.2.2
      - accelerate==1.6.0
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.12
      - aiosignal==1.3.2
      - anyio==4.8.0
      - appnope==0.1.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - astunparse==1.6.3
      - async-lru==2.0.4
      - async-timeout==5.0.1
      - attrs==24.3.0
      - audioread==3.0.1
      - babel==2.16.0
      - backports-tarfile==1.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - certifi==2024.12.14
      - cffi==2.0.0
      - charset-normalizer==3.4.1
      - colormath==3.0.0
      - colorutils==0.3.0
      - colour==0.1.5
      - comm==0.2.2
      - contourpy==1.3.1
      - cryptography==46.0.3
      - cycler==0.12.1
      - cython==3.0.12
      - debugpy==1.8.12
      - decorator==5.1.1
      - defusedxml==0.7.1
      - eelbrain==0.41.2
      - et-xmlfile==2.0.0
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fastjsonschema==2.21.1
      - fasttext==0.9.3
      - filelock==3.13.1
      - flatbuffers==25.2.10
      - fonttools==4.55.3
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - gammatone==1.0.3
      - gast==0.6.0
      - gdist==2.1.0
      - gensim==4.3.3
      - google-pasta==0.2.0
      - grpcio==1.71.0
      - h11==0.14.0
      - h5py==3.12.1
      - hdf5storage==0.1.19
      - hf-xet==1.1.0
      - himalaya==0.4.6
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.31.1
      - idna==3.10
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - ipyevents==2.0.2
      - ipykernel==6.29.5
      - ipython==8.31.0
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.3.0
      - jedi==0.19.2
      - jeepney==0.9.0
      - jinja2==3.1.5
      - joblib==1.4.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.11.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-proxy==4.4.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kenlm==0.3.0
      - keras==3.9.2
      - keyring==25.6.0
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - libclang==18.1.1
      - librosa==0.11.0
      - llvmlite==0.44.0
      - lxml==5.3.1
      - markdown==3.8
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - meegkit==0.1.7
      - mido==1.3.3
      - mistune==3.1.0
      - ml-dtypes==0.5.1
      - mne==1.9.0
      - mne-bids==0.16.0
      - more-itertools==10.6.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - mtrf==2.0.5
      - multidict==6.1.0
      - namex==0.0.9
      - naplib==2.5.0
      - narwhals==1.28.0
      - nbclient==0.10.2
      - nbconvert==7.16.5
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - nibabel==5.3.2
      - nilearn==0.11.1
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - numba==0.61.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optree==0.15.0
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - pandas-flavor==0.6.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - patsy==1.0.1
      - pexpect==4.9.0
      - pillow==11.1.0
      - pingouin==0.5.5
      - platformdirs==4.3.6
      - plotly==6.0.0
      - pooch==1.8.2
      - praat-textgrids==1.4.0
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - propcache==0.2.1
      - protobuf==5.29.4
      - psignifit==4.3
      - psutil==6.1.1
      - psutils==3.3.11
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - puremagic==1.30
      - pybind11==2.13.6
      - pycparser==2.22
      - pygments==2.19.1
      - pymatreader==1.0.0
      - pyparsing==3.2.1
      - pypdf==6.1.2
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.16
      - pyqt5-sip==12.17.0
      - pyriemann==0.7
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.2.1
      - pytz==2024.2
      - pyvista==0.44.2
      - pyvistaqt==0.11.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - qtpy==2.4.3
      - referencing==0.36.1
      - regex==2024.11.6
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==14.0.0
      - rpds-py==0.22.3
      - safetensors==0.5.3
      - scikit-learn==1.6.0
      - scikit-spatial==8.1.0
      - scipy==1.13.1
      - scooby==0.10.0
      - seaborn==0.13.2
      - secretstorage==3.4.0
      - send2trash==1.8.3
      - simpervisor==1.0.0
      - six==1.17.0
      - smart-open==7.1.0
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soupsieve==2.6
      - soxr==0.5.0.post1
      - stack-data==0.6.3
      - statsmodels==0.14.4
      - sympy==1.13.1
      - tabulate==0.9.0
      - tdt==0.6.7
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.1.0
      - terminado==0.18.1
      - textgrid==1.6.1
      - tf-keras==2.19.0
      - threadpoolctl==3.5.0
      - tinycss2==1.4.0
      - tokenizers==0.21.1
      - tomli==2.2.1
      - torch==2.6.0+cu124
      - torchaudio==2.6.0+cu124
      - torchvision==0.21.0+cu124
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - trame==3.8.0
      - trame-client==3.5.2
      - trame-server==3.3.0
      - trame-vtk==2.8.15
      - trame-vuetify==2.8.1
      - transformers==4.51.3
      - triton==3.2.0
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.15.0
      - tzdata==2024.2
      - uri-template==1.3.0
      - urllib3==2.3.0
      - vtk==9.3.1
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.13
      - wrapt==1.17.2
      - wslink==2.2.2
      - xarray==2025.1.2
      - xmltodict==0.14.2
      - yarl==1.18.3
      - zipp==3.23.0
prefix: /data/u_barchet_software/miniconda3/envs/mne_new
